### PR TITLE
fixed configuration in knexfile.js for proper local postgres set up. …

### PR DESCRIPTION
**Pull request by Air-Bear**
…Also moved knexfile.js from config to root folder because the path wasn't resolving correctly when calling knex commands from terminal.

### CODE REVIEW

**Review by desicurry — APPROVED** [review]
Looks like this makes it easier for the backend to run locally.

**Review by JChinchilla91 — COMMENTED** [review]
I see in your package.json you have a newer version of knex installed. Not sure if that'll create any problems for us. I'm going to check if so, lemme know if you find out.

**Review by BrianM-218 — COMMENTED** [review]
Line 10 adds Postgres, but Josh and I are using ElephantSQL, will this interfere with anything?

**Comment by JasonRHemann** [comment]
We are gonna bypass the missing .env.sample file

**Comment by Air-Bear** [comment]
> Line 10 adds Postgres, but Josh and I are using ElephantSQL, will this interfere with anything?

Judging from how ElephantSQL ignored the initially erroneous knexfile, it would appear to me that it shouldn't be an issue. I'm not sure how ElephantSQL exactly works however, so if someone else has any further insight, feel free to correct me.

**Pull request merged**
